security:

    encoders:
        AppBundle\Entity\Users:
            algorithm: bcrypt
            cost: 12
    
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        
    providers:
        myProvider:
            entity:
                class: AppBundle:Users

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            provider: myProvider
            form_login:
                login_path:  login
                check_path:  login
                default_target_path: homepage
            logout:
                path:   /logout
                target: /login
                
                
                
    access_control:
        - {path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - {path: ^/, roles: {ROLE_USER, ROLE_ADMIN} }
        